[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

# Next.js specific settings
[context.production.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "false"